mybatis:
  typeAliasesPackage: com.longfor.gaia.gfs.data.mybatis.po
  mapperLocations:
    - classpath:mapper/*.xml
  mapper:
    notEmpty: true


spring:
  datasource:
    username: sa
    password:
    schema: classpath:db/schema.sql

    #多数据源配置
    dynamic:
      primary: master
      datasources:
        master:
          #默认数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:mem:db_master;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: user_master
          password:
          druid:
            filters: stat
            max-active: 20
            initial-size: 1
            max-wait: 30000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            remove-abandoned: true
            remove-abandoned-timeout-millis: 500000
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/download/*,/wj/*,/assets/*'
        custom01:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:mem:db_custom01;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: user_custom01
          password:
          hikari:
            #控制从池返回的连接的默认自动提交行为。默认值：true
            auto-commit: true
            #客户端等待连接的最大毫秒数。如果在没有可用连接的情况下超过此时间，则会抛出SQLException。默认值：30000
            connection-timeout: 10000
            #此属性控制允许连接在池中闲置的最长时间。此设置仅适用于minimumIdle定义为小于maximumPoolSize。默认值：600000（10分钟）
            idle-timeout: 600000
            #此属性控制池中连接的最大生存期。默认值：1800000（30分钟）
            max-lifetime: 1800000
            #该属性控制HikariCP尝试在池中维护的最小空闲连接数。默认值：与maximumPoolSize相同
            minimum-idle: 10
            #此属性控制池允许达到的最大大小，包括空闲和正在使用的连接。默认值：10
            maximum-pool-size: 10
        custom02:
          driver-class-name: org.h2.Driver
          jdbc-url: jdbc:h2:mem:db_custom02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: user_custom02
          password: