spring:
  application:
    name: @project.name@

  profiles:
    active: @profileActive@

  main:
    allow-bean-definition-overriding: true

server:
  port: 62001

#应用基本信息
info:
  project:
    name:  @project.name@
    version: 1.0.0
